#!/bin/bash
#bdereims@vmware.com

# this file is not synced in git
. ./env.passwd

SLACK=NO
LEASE=NO

ROOT_DOMAIN="az-demo.shwrfr.com"

# Transit LS for cPodRouter connectivity
TRANSIT=172.19
ASN=65100

TRANSIT_NET="172.16"
DNS="${TRANSIT_NET}.1.1"

CLUSTER="INTEL"
HEADER="cPod"

NETWORK_DIR=network
COMPUTE_DIR=compute
EXTRA_DIR=extra

NSX=10.1.0.152
NSX_ADMIN="admin"
NSX_TRANSPORTZONE="TransportZone"

ISO_BANK_SERVER="10.1.0.51"
ISO_BANK_DIR="/VNXeDatastore/ISO-Bank"

VCENTER=10.1.0.29
VCENTER_ADMIN="cpod@intel.lab"
VCENTER_DATACENTER="INTEL-LAB"
VCENTER_CLUSTER="INTEL Cluster"
TEMPLATE_VM="template-cPodRouter"
#TEMPLATE_ESX="template-ESX67U3"
TEMPLATE_ESX="template-ESX70beta"
TEMPLATE_FILER="template-cPodFiler"
DATASTORE=${DATASTORE:="INTEL-VSAN"}
