name: Tests

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:

  shfmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64 -o shfmt
          chmod a+x shfmt
      - run: ./shfmt --diff .

  linux:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        env_vars:
          - ''
          # allow for some parallelity without GNU parallel, since it is not installed by default
          - 'BATS_NO_PARALLELIZE_ACROSS_FILES=1 BATS_NUMBER_OF_PARALLEL_JOBS=2'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run test on OS ${{ matrix.os }}
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: |
          bash --version
          bash -c "time ${{ matrix.env_vars }} test/bats/bin/bats --print-output-on-failure --formatter tap test"
